name: Update Location

on:
  schedule:
    # Run every day at midnight UTC
    - cron: '0 0 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-github-location:
    name: Update GitHub Profile Location
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - run: npm ci
      
      - name: Update GitHub Location
        run: npm run set:github-location
        env:
          # Note: We need a Personal Access Token with 'user' scope here
          # The default GITHUB_TOKEN doesn't have permissions to update user profile
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
